const Website = {
batch_2024:[
  {
    id: 1,
    sname: "CHANCHAL SONI",
    image: "../images/00106142019_Chanchal.jpg ",
    resume: "../pdfs/00106142019_Chanchal.pdf",
    interest: "Interior Design, Healthcare Design, Interaction Design, BIM",
  },
  {
    id: 2,
    sname: "YASHMITA BANDARI",
    image: "../images/00206142019_yashmita bandari.jpg ",
    resume: "../pdfs/00206142019_Bandari Yashmita.pdf",
    interest: "Urban design, UI/UX",

  },
  {
    id: 3,
    sname: "KANCHAN",
    image: "../images/00306142019-Kanchan.png",
    resume: "../pdfs/00306142019--Kanchan.pdf",
    interest: "BIM, Urban design",

  },

  {
    id: 4,
    sname: "NANDITA",
    image: "../images/00406142019_Nandita.png",
    resume: "../pdfs/00406142019_Nandita.pdf",
    interest: "Urban Design, BIM, Urban planning ",

  },
  {
    id: 5,
    sname: "SUPREENA DASH",
    image: "../images/00506142019- Supreena Dash_.jpg",
    resume: "../pdfs/00506142019- Supreena Dash_.pdf",
    interest: "Urban design, UI/UX",
  },
  {
    id: 6,
    sname: "DIKSHA DHANTRI",
    image: "../images/00606142019_diksha dhantri.jpg",
    resume: "../pdfs/00606142019_diksha dhantri.pdf",
    interest: "Experiential design , UI/UX , Production design",
  },
  {
    id: 7,
    sname: "KANISHKA PAL",
    image: "../images/00706142019-Kanishka Pal.jpg",
    resume: "../pdfs/00706142019-Kanishka Pal.pdf",
    interest: "Conservation, Landscape Architecture ",
  },
  {
    id: 8,
    sname: "SHRUTI KALGAONKAR",
    image: "../images/00806142019-Shruti Kalgaonkar_.jpg",
    resume: "../pdfs/00806142019- Shruti Kalgaonkar_.pdf",
    interest: "Experiential design , UI/UX , Production design",
  },
  {
    id: 9,
    sname: "ZARQA REHMAN",
    image: "../images/00906142019_Zarqa_.jpg",
    resume: "../pdfs/00906142019_Zarqa Rehman.pdf",
    interest: "Urban Planning, Journalism and Conservation ",
  },
  {
    id: 10,
    sname: "SHREYA JAIN",
    image: "../images/01006142019_Shreya Jain.jpg",
    resume: "../pdfs/01006142019_Shreya Jain.pdf",
    interest: "Residential design, Hospitality design, Landscape Architecture ",
  },
  {
    id: 11,
    sname: "EKTA DHIMAN",
    image: "../images/01106142019-Ekta Dhiman.jpg",
    resume: "../pdfs/01106142019- Ekta Diman.png",
    interest: "Computational Designing, Robotics ",
  },
  {
    id: 12,
    sname: "ANUSHKA",
    image: "../images/01206142019-Anushka.jpg",
    resume: "../pdfs/01206142019_Anushka.pdf",
    interest: "Ui n Ux, interaction design, landscape architecture, bim, masters after doing job for a year",
  },
  {
    id: 13,
    sname: "TEESTA",
    image: "../images/01306142019_Teesta.jpg",
    resume: "../pdfs/01306142019_Teesta.pdf",
    interest: "Ephemeral & experiential design, Research, Public policy, Industrial design, barrier free designs,Urban planning",
  },
  {
    id: 14,
    sname: "SUPRIYA SAMANTA",
    image: "../images/img10.jpg",
    resume: "../pdfs/01406142019_Supriya Samanta CV.pdf",
    interest: "Design in Architecture, Parametric Design, Human computer interaction ",
  },
  {
    id: 15,
    sname: "RIDHI",
    image: "../images/01506142019_Riddhi.jpg",
    resume: "../pdfs/01506142019_Riddhi.pdf",
    interest: "exhibition design, new media design, production design, design",
  },
  {
    id: 16,
    sname: "ANKITA ARYA",
    image: "../images/01606142019_Ankita Arya.PNG",
    resume: "../pdfs/01606142019_Ankita Arya.pdf",
    interest: "BIM, Urban design",
  },
  {
    id: 17,
    sname: "DEVANSHI JAIN",
    image: "../images/01806142019_Devanshi Jain.jpg",
    resume: "../pdfs/01806142019_Devanshi Jain.pdf",
    interest: "Healthcare design, landscape architecture",
  },
  {
    id: 18,
    sname: "SONA GUSSAIN",
    image: "../images/01906142019_Sona gusain_.jpg",
    resume: "../pdfs/01906142019_Sona Gusain.pdf",
    interest: "BIM, Urban design",
  },
  {
    id: 19,
    sname: "KUSUM JAREDA",
    image: "../images/02106142019 - Kusum Jareda_.jpg",
    resume: "../pdfs/02106142019- Kusum Jareda.pdf",
    interest: "BIM, Urban design",
  },
  {
    id: 20,
    sname: "ADITI KUMARI",
    image: "../images/img9.jpg",
    resume: "../pdfs/02206142019- Aditi Kumari.pdf",
    interest: "Residential design , urban planning ,",
  },
  {
    id: 21,
    sname: "PALAK VERMA",
    image: "../images/02306142019_PALAK VERMA.jpg",
    resume: "../pdfs/02306142019_PALAK VERMA_CV.png",
    interest: "BIM, Urban design",
  },
  {
    id: 22,
    sname: "SHREYA SUMAN",
    image: "../images/02406142019- Shreya Suman.png",
    resume: "../pdfs/02406142019- Shreya Suman.pdf",
    interest: "Research, Public Policy, Academia, Urban Planning, Construction Management",
  },
  {
    id: 23,
    sname: "ANCHAL",
    image: "../images/02606142019_anchal.jpg",
    resume: "../pdfs/02606142019_Anchal.pdf",
    interest: "BIM, project management,Urban planning",
  },
  {
    id: 24,
    sname: " SADIYA IQBAL ",
    image: "../images/02706142019 sadiya iqbal_.jpg",
    resume: "../pdfs/02706142019 sadiya_.pdf",
    interest: "visual communication, industrial designer, urban design ,BIM",
  },
  {
    id: 25,
    sname: "DEEPSHA GOSWAMI",
    image: "../images/02806142019_Deeksha Goswami.png",
    resume: "../pdfs/02806142019_DeekshaGoswami.pdf",
    interest: "Interior Design, Suistainable Architecture, Housing and Hospitality Design",
  },
  {
    id: 26,
    sname: "MISHTI MADAN",
    image: "../images/02906142019- Mishti Madan.PNG",
    resume: "../pdfs/02906142019 - Mishti Madan.pdf",
    interest: "BIM, Urban design",
  },
  {
    id: 27,
    sname: "JAHANVI",
    image: "../images/03006142019-jahanvi.jpg",
    resume: "../pdfs/03006142019_Jahanvi.pdf",
    interest: "BIM, Urban design",
  },
  {
    id: 28,
    sname: "JYOTI",
    image: "../images/03106142019_Jyoti.jpeg",
    resume: "../pdfs/03106142019_Jyoti.pdf",
    interest: "BIM, Urban design",
  },
  {
    id: 29,
    sname: "KALPANA PANDEY",
    image: "../images/03206142019_Kalpana Pandey.png",
    resume: "../pdfs/03206142019_Kalpana Pandey.pdf",
    interest: "BIM, Urban design",
  },
  {
    id: 30,
    sname: "PRAGATI KUMARI",
    image: "../images/03306142019- Pragati Kumari.jpg",
    resume: "../pdfs/03306142019 pragati kumari.pdf",
    interest: "BIM, journalism, research, urban design",
  },
  {
    id: 31,
    sname: "KAJAL PRAJAPATI",
    image: "../images/03406142019_Kajal Prajapati_.jpg",
    resume: "../pdfs/03406142019_Kajal Prajapati_.pdf",
    interest: "BIM, Urban design",
  },
  {
    id: 32,
    sname: "GARIMA",
    image: "../images/03506142019_Garima.jpg",
    resume: "../pdfs/03506142019_Garima_.pdf",
    interest: "Airport Designing ",
  },
  {
    id: 33,
    sname: "RICHA KUMARI",
    image: "../images/03606142019_richa kumari.jpg",
    resume: "../pdfs/03606142019_Richa Kumari.pdf",
    interest: "Urban planning & Design, Computational modelling",
  },
],
batch_2025:[
  { id: 1,
    sname: "GURPRIYA SINGH",
    image:"../images/1.jpg ",
    resume:"../pdfs/001_Gurpriya Singh.pdf",
    intrest:"Design Thinking, Interior Design, Rendering, 3D Visualisation, Construction Drawings",
    introduction:"I believe we can make the world a better and more sustainable place through creativity and attention to detail ",
    },
    { id: 2,
    sname: "RIYA GOEL",
    image:"../images/2.jpeg ",
    resume:"../pdfs/00206142020_Riya goel.pdf",
    intrest:"Design thinking, interior design , 3d renders, working drawings",
    introduction:"To put my best step forward in order to accomplish the goals and objectives of the firm using ny skill set , talent and passion while persistently working towards personal development",
    },
    { id: 3,
    sname: "ANKITA PILANIYA",
    image:"../images/3.jpg",
    resume:"../pdfs/003_ANKITA PILANIYA.pdf",
    intrest:"design management, research, residential projects, journalism, writing",
    introduction:" As a lifelong learner, I want to stay at the forefront of emerging architectural trends, materials, and technologies. I am dedicated to continuously expanding my knowledge and skill set.",
    },
    { id: 4,
    sname: "TANYA BHATIA",
    image:"../images/4.jpg",
    resume:"../pdfs/00406142020-_Tanya.pdf",
    intrest:"rendering,working drawings,3d renders,journalism,interior designs",
    introduction:"I'm a student studying architecture, and I'm enthusiastic about crafting imaginative and environmentally-conscious designs. ",
    
    },
    { id: 5,
    sname: "NIDHI SHARMA",
    image:"../images/5.jpeg",
    resume:"../pdfs/00506142020_nidhi.pdf",
    intrest:"Interior Design, Working Drawings, Rendering ",
    introduction:"I'm an architecture student on a transformative journey, where my passion for creating inspiring spaces has driven both my personal growth and development in the field.",
    
    },
    { id: 6,
    sname: "JANHAVI SEHGAL",
    image:"../images/6.jpg",
    resume:"../pdfs/00606142020_janhavisehgal.pdf",
    intrest:"Design thinking, interior design, working drawings, rendering ",
    introduction:"Unlocking doors with words and crafting success, I live by Mark Twain's wisdom: 'The secret of getting ahead is getting started. As a dedicated architecture student with a passion for innovative design and sustainable solutions, I am eager to apply my creative skills and academic knowledge to contribute to meaningful projects and prepared to collaborate and learn in a dynamic professional environment.",
    
    },
    { id: 7,
    sname: "YASHIKA",
    image:"../images/7.jpg",
    resume:"../pdfs/00706142020_Yashika.pdf",
    intrest:"Design thinking, working drawings, interior and landscape design, 3d rendering",
    introduction:"I am an architecture student, dedicated to creating spaces that blend aesthetic beauty with practical functionality, and I'm eager to embark on a journey where creativity meets construction",
    },
    { id: 8,
    sname: "MAHIRA KHAN",
    image:"../images/8.jpg",
    resume:"../pdfs/00806142020_mahira.pdf",
    intrest:"Design thinking, working drawings, interior and landscape design, 3d rendering",
    introduction:"I am a keen, observant learner in the field of design and architecture , I believe that experience is the primary tool to chart out the design one seeks to produce. Everyday experiences influence my choice of architecture ",
    },
    { id: 9,
    sname: "SHREYA BANSAL",
    image:"../images/9.jpg",
    resume:"../pdfs/00906142020_shreya bansal.pdf",
    intrest:"Interior design,3d visualisation,3d rendering,landscaping",
    introduction:"",
    },
    { id: 10,
    sname: "NANDINI GUPTA",
    image:"../images/10.png",
    resume:"../pdfs/01006142020_Nandini Gupta.pdf",
    intrest:"Design thinking, working drawings, Photoshop renders, 3D modelling, BIM",
    introduction:"I am a creative person with a love for art, graphics, and architecture and a passion for design thinking and problem-solving. Architecture is the art of designing and constructing something for a specific purpose with the ability to enhance the urban form.",
    },
    { id: 11,
    sname: "RUCHIKA PANJA",
    image:"../images/11.jpg",
    resume:"../pdfs/01106142020_RUCHIKA PANJA.pdf",
    intrest:"design thinking, 3D visualisation, rendering, BIM, GIS",
    introduction:"I am a keen architecture student and observer, a problem solver, well versed in creative design, and self motivated. I am passionate about learning and creating innovative and sustainable solutions.",
    },
    { id: 12,
    sname: "MANSIDAQUE KAUR",
    image:"../images/12.png",
    resume:"../pdfs/01206142020_MansidaqueKaur.pdf",
    intrest:"Working Drawings, Construction Management & BIM, Interior Design",
    introduction:"Passionate individual in the ability of designing & dedicated to the architectural exellence, driven by creativity and diligence. ",
    },
    { id: 13,
    sname: "SHEJAL",
    image:"../images/13.jpg",
    resume:"../pdfs/01306142020_Shejal Gupta.pdf",
    intrest:"Design thinking, interior design, working drawings",
    introduction:"",
    },
    { id: 14,
    sname: "HARSHITA JOSHIA PRADHAN",
    image:"../images/14.jpg",
    resume:"../pdfs/01406142020_Harshita joshia Pradhan_.pdf",
    intrest:"Construction management, interior design, rendering & Working drawings ",
    introduction:"I'm an architecture student passionate about designing spaces that inspire and uplift.I'm excited to learn and grow in the field of architecture, construction project management & real estate, and I'm eager to make a positive impact on the world through my work",
    },
    { id: 15,
    sname: "VAIDEHI VARSHNEY",
    image:"../images/15.jpg",
    resume:"../pdfs/01506142020_Vaidehi Varshney.pdf",
    intrest:"working drawing, design thinking, journalism, rendering 3d, residential projects and hospital design",
    introduction:"I am a young & passionate, future Architect with a thorough grasp of the principles of Design & Architecture, paired with a handful of skills related to the field & otherwise",
    },
    { id: 16,
    sname: "VARSHA VATS",
    image:"../images/16.jpg",
    resume:"../pdfs/01606142020_varsha vats.pdf",
    intrest:"Residentials, Housing, Architecture and Interior Design",
    introduction:"Passionate architecture student, weaving creativity and functionality into every design. Eager to shape spaces that enrich lives.Design is not just what it looks like and feels like. Design is how it works.",
    },
    { id: 17,
    sname: "PAYAL",
    image:"../images/17.jpg",
    resume:"../pdfs/01706142020_Payal yadav.pdf",
    intrest:"Design thinking, Working drawings, commercial design.",
    introduction:"",
    },
    { id: 18,
    sname: "AKSHITA JHA",
    image:"../images/18.jpg",
    resume:"../pdfs/01806142020_AKSHITAJHA.pdf",
    intrest:"Design thinking, interior design, rendering, 3D visualisation",
    introduction:"A meticulus student of Architecture with a passion of learning and designing, I believe Architecture is a time stamp that we leave as our mark in the world. ",
    },
    { id: 19,
    sname: "RUPSHA GHOSH",
    image:"../images/19.jpg",
    resume:"../pdfs/01906142020_Rupsha Ghosh.pdf",
    intrest:"Interior design, 3d modeling ,3d rendering, architectural journalism, content writing ",
    introduction:"",
    },
    { id: 20,
    sname: "KASHVI NATHALA",
    image:"../images/20.jpg",
    resume:"../pdfs/02006142020_Kashvi Nathala.pdf",
    intrest:"Design thinking, Working drawings, commercial design",
    introduction:"I'm an ambitious architecture student with a passion for creating immersive and aesthetically captivating spaces and a strong eye for details. My diverse interest in various fields can bring fresh perspectives to design challenges and unique insights from other disciplines, paired with software skills can help enhance architectural solutions.",
    },
    { id: 21,
    sname: "BHAWNA JHA",
    image:"../images/21.jpg",
    resume:"../pdfs/02206142020_Bhawna Jha_.pdf",
    intrest:"BIM/3D visualisaion & modelling, Designing/planning(GIS), working drawing/drafting, research",
    introduction:"",
    },
    { id: 22,
    sname: "SAKSHI SINGH",
    image:"../images/22.jpg",
    resume:"../pdfs/02306142020_SakshiSingh.pdf",
    intrest:"Interior Design, Rendering, Design thinking, commercial/residential design, Landscape design, Vastu Design  ",
    introduction:"",
    },
    { id: 23,
    sname: "NIYA SHARMA",
    image:"../images/23.jpg",
    resume:"../pdfs/02406142020_NIYA.pdf",
    intrest:"parametric design,interior design,material research,3d visualisation ",
    introduction:"",
    },
    { id: 24,
    sname: "SHATAKSHI KASHYAP",
    image:"../images/24.png",
    resume:"../pdfs/02506142020_Shatakshi_Kashyap.pdf",
    intrest:"Set design, graphic design, working drawings and research ",
    introduction:"A blend of passion and ingenuity in one person; drawn to the silent narratives etched within the bricks and mortar, where every space whispers its own tale. ",
    },
    { id: 25,
    sname: "RIA SAINI",
    image:"../images/25.jpg",
    resume:"../pdfs/02606142020_Riasaini.pdf",
    intrest:"Interior Design, Rendering, Working Drawing, Research ",
    introduction:"I am an architecture student whose journey in this field has been a profound personal growth experience. From early sketches to pursuing innovative solutions, my dedication to architecture has not only shaped my design structures but also pushed me to discover and expand my own potential",
    },
    { id: 26,
    sname: "APOORVA BHALOTIA",
    image:"../images/26.jpg",
    resume:"../pdfs/02706142020_Apoorva.pdf",
    intrest:"Residential Design, Interior Design (BIM, 3D Visualisation, Design, Render, Working Drawings)",
    introduction:"I am an ambitious architecture student with a profound passion for interior design in both residential and commercial domains. My unique blend of creative vision, technical acumen, and a client-centric approach makes me an invaluable addition to any design firm. With a commitment to innovation and a dedication to creating functional and aesthetically pleasing spaces. ",
    },
    { id: 27,
    sname: "HARSHITA AZAD",
    image:"../images/27.jpg",
    resume:"../pdfs/02806142020_Harshita_Azad.pdf",
    intrest:"Interior design, working drawings, research ",
    introduction:"Simple with a focus on clean, functional design and a dedication to timeless aesthetics.",
    },
    { id: 28,
    sname: "PREETI RAWAT",
    image:"../images/28.jpg",
    resume:"../pdfs/02906142020-Preeti Rawat.pdf",
    intrest:"Interior Design, Rendering, 3D Visualisation, Working Drawings",
    introduction:"I am a dedicated individual with a passion for architecture, seeking opportunities to contribute my skills and expertise.",
    },
    { id: 29,
    sname: "AVANTIKA CHHETRI",
    image:"../images/29.png",
    resume:"../pdfs/Avantika (2).pdf",
    intrest:"residential, hospitality projects, , interior, working drawing",
    introduction:"",
    },
    { id: 30,
    sname: "SIMRAN SINGH",
    image:"../images/30.jpg",
    resume:"../pdfs/03206142020_Simran singh.pdf",
    intrest:"exhibition organising, architecture journalism,working drawings, interior design , ",
    introduction:"Cultivating designs that marry the elegance of the past with the possibilities of the future, I aspire to be the architect who bridges tradition and innovation. I'll be grateful if I get a chance to work and grow my skills.",
    },
    { id: 31,
    sname: "JYOTI GUPTA",
    image:"../images/31.jpg",
    resume:"../pdfs/03306142020_Jyoti Gupta.pdf",
    intrest:"working drawing, BIM/3D Visualization and modelling, rendering",
    introduction:"",
    },
    { id: 32,
    sname: "RAMYA GUPTA",
    image:"../images/32.jpg",
    resume:"../pdfs/CV.pdf",
    intrest:"Design management, research ",
    introduction:"I am an architectural student who will deliver high quality work with exceptional attention to function and details. I strongly believe in my passionate personal involvement at all stages of design and execution.",
    },
    { id: 33,
    sname: "AKSHITA RAWAT",
    image:"../images/33.jpg",
    resume:"../pdfs/",
    intrest:"Architectural Research and Writing, Design Management, Content Writing",
    introduction:"",
    },
    { id: 34,
    sname: "KRITI YADAV",
    image:"../images/34.jpeg",
    resume:"../pdfs/kriti.pdf",
    intrest:"Residential design, Interior Design, Design Thinking,3D Modelling,rendering,commercial design,working drawings,Research",
    introduction:"",
    },
    { id: 35,
    sname: "SAFALTA PRASAD",
    image:"../images/35.jpg",
    resume:"../pdfs/03706142020_SafaltaPrasad.pdf",
    intrest:"Design Thinking, GIS, Interior Design, Rendering, 3D Visualisation ",
    introduction:"",
    },
    { id: 36,
    sname: "ANKITA",
    image:"../images/36.jpg",
    resume:"../pdfs/03806142020 Ankita.jpg",
    intrest:"3d visualization and modelling, interior and facade designing, Sustainable design conceptualization ",
    introduction:"",
    },
    { id: 37,
    sname: "TITIKSHA MISHRA",
    image:"../images/37.jpg",
    resume:"../pdfs/03906142020 _ Titiksha Mishra.pdf",
    intrest:"Healthcare design, Residential design, Landscaping, 3d visualization, facade designing ",
    introduction:"",
    },
    { id: 38,
    sname: "KAREENA",
    image:"../images/38.jpg",
    resume:"../pdfs/04006142020_kareena.pdf",
    intrest:"Healthcare design, interior design, landscape design and 3d visualization",
    introduction:"",
    },
    { id: 39,
    sname: "KANCHAN SINGH",
    image:"../images/39.jpg",
    resume:"../pdfs/04106142020_Kanchan Singh.pdf",
    intrest:"3D modeling, BIM, Working drawings, rendering, Residential and commercial design, interior designing ",
    introduction:"I am a fourth year architecture student from Indira Gandhi Delhi Technical University. I have been doing significant work with design strategy . I am a consistent person and give my best to meet my deadlines. As an architecture student I try to create a harmonious, thoughtful and accommodative environment for all.",
    },
    { id: 40,
    sname: "FALAK REHMAN",
    image:"../images/40.jpg",
    resume:"../pdfs/04206142020.pdf",
    intrest:"Residential design, Interior Design, Design Thinking,3D Modelling,rendering,commercial design,working drawings,Research	",
    introduction:"Highly skilled architecture student with experience in design principles, construction techniques, and project management, seeking opportunities to apply knowledge and skills in the field.",
    },
    { id: 41,
    sname: "ISHPREET KAUR",
    image:"../images/.jpg",
    resume:"../pdfs/",
    intrest:"Architectural Research and Writing, Design Management, Content Writing",
    introduction:"",
    },
    { id: 42,
    sname: "AVANTIKA VERMA",
    image:"../images/42.jpg",
    resume:"../pdfs/04406142020.pdf",
    intrest:"Residential design, Interior Design, Design Thinking,3D Modelling,rendering,commercial design,working drawings,Research",
    introduction:"Motivated and creative architecture student with a passion for innovative design solutions and sustainability, seeking opportunities to contribute to meaningful projects and gain valuable industry experience.",
    },
    { id: 43,
    sname: "SHIVANSHI AGGARWAL",
    image:"../images/43.jpg",
    resume:"../pdfs/04506142020_Shivanshi aggarwal.pdf",
    intrest:"commercial projects , interior design , landscaping design , design thinking , residential design",
    introduction:"I am keen, observant learner in the field of architecture .I have kept myself in doing significant work with good design strategy and visual identity.I embrace challanges and constantly seek opportunities for my personal and professional growth .I highly value innovation in my intrest and constantly strive to put it forth through my work, academically and co-curricularly.",
    },
    { id:44,
    sname: "MEGHA SINGH",
    image:"../images/44.jpg",
    resume:"../pdfs/04606142020_Megha Singh.pdf",
    intrest:"Residential design, Interior design, working drawings",
    introduction:"I am a budding architect who understands the power of architecture as a medium of change in society. I strive to include the user and inhabitants perspective and focus more on the experience and functionality while designing a particular space. I am a strong supporter of sustainable and vernacular architecture but also value the role of innovation and other emerging architectural phenomenon. I believe that sustainable design is an integration of passive design techniques, vernacular materials and creativity which has ability to create a healthy built environment and solve some of the world's modern issues and I aspire to be part of that change.",
    },
    { id: 45,
    sname: "SANSKRITI GUPTA",
    image:"../images/45.jpg",
    resume:"../pdfs/04706142020_Sanskriti Gupta.pdf",
    intrest:"Residential design, Design management, Architectural journalism and Writing ",
    introduction:"I have a passion for creating innovative and sustainable design solutions. Adept at utilizing cutting-edge software and technology to bring ideas to life, I strive to push the boundaries of creativity andfunctionality in every project I undertake.",
    },
    { id: 46,
    sname: "NISHTHA DHAMIJA",
    image:"../images/46.jpg",
    resume:"../pdfs/04806142020_nishtha.pdf",
    intrest:"residential design, commercial projects, landscaping design, 3d visualisation, design thinking and working drawings",
    introduction:"Diligent architecture student, blending creativity with precision. Skilled in tech tools, thrive in teams, and always eager to grow professionally in architecture.",
    },
],
};
export default Website;
